---
- name: Install WordPress
  hosts: wordpress
  become: true

  vars:
    db_name: wordpress
    db_user: wpadmin
    db_password: P@ssword1
    db_root_password: rootP@ssword1

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
  
    - name: Install required packages
      apt:
        name:
          - apache2
          - python3-pymysql
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
        state: present
      become: true

    - name: Start and enable Apache2
      service:
        name: apache2
        state: started
        enabled: true

    - name: Remove default Apache index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: true

    - name: Change MySQL root user
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ db_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Create WordPress database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_host: localhost
        login_user: root
        login_password: "{{ db_root_password }}"

    - name: Create MySQL user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_host: localhost
        login_user: root
        login_password: "{{ db_root_password }}"

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions
      file:
        path: /var/www/html
        recurse: yes
        owner: www-data
        group: www-data
    
    - name: Copy WordPress config
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wp-config.php

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted