---
- name: Azure Infrastructure Deployment
  hosts: localhost
  connection: local
  vars:
    resource_group: KE02_groep02_RG
    location: West Europe
    virtual_network: TestVnet
    address_prefixes: "10.15.0.0/16"
    admin_username: azureadmin
    ssh_key_path: "keys/azureadmin.pub"

  tasks:
    # Create Virtual Network
    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        location: "{{ location }}"
        address_prefixes: "{{ address_prefixes }}"

    # Create subnets
    - name: Create subnets
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network: "{{ virtual_network }}"
        name: "{{ item.name }}"
        address_prefix: "{{ item.prefix }}"
      loop:
        - { name: "Front-End", prefix: "10.15.0.0/24" }
        - { name: "Back-End", prefix: "10.15.1.0/24" }
        - { name: "Stepping-Stone", prefix: "10.15.2.0/24" }

    # Create Network Security Groups (NSGs)
    - name: Create Network Security Groups (NSGs)
      command: >
        az network nsg create
        --resource-group "{{ resource_group }}"
        --name "{{ item.name }}"
        --location "{{ location }}"
      loop:
        - { name: "NSG-Front-End" }
        - { name: "NSG-Back-End" }
        - { name: "NSG-Stepping-Stone" }

    # Create Network Interface for Virtual Machine
    - name: Create Network Interface for Virtual Machine
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}-nic"
        location: "{{ location }}"
        subnet_name: "{{ item.subnet }}"
        virtual_network: "{{ virtual_network }}"
        security_group: "{{ item.nsg }}"
        ip_configurations:
          - name: ipconfig1
            private_ip_address: "{{ item.private_ip }}"
            private_ip_allocation_method: "Static"
            public_ip_address_name: "{{ item.name }}-public-ip"
            public_ip_allocation_method: "{{ 'Static' if item.public_ip else 'Dynamic' }}"
      loop:
        - { name: "VM-Front-End", subnet: "Front-End", nsg: "NSG-Front-End", public_ip: true, private_ip: "10.15.0.4" }
        - { name: "VM-Back-End", subnet: "Back-End", nsg: "NSG-Back-End", public_ip: false, private_ip: "10.15.1.4" }
        - { name: "VM-Stepping-Stone", subnet: "Stepping-Stone", nsg: "NSG-Stepping-Stone", public_ip: true, private_ip: "10.15.2.4" }

    # Create Virtual Machines
    - name: Create Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        location: "{{ location }}"
        vm_size: Standard_B1ls
        admin_username: "{{ admin_username }}"
        admin_password: "LengthyP@ssword1"
        ssh_password_enabled: yes
        image:
          offer: ubuntu-24_04-lts
          publisher: Canonical
          sku: server
          version: latest
        os_disk_name: "{{ item.name }}-osdisk"
        os_disk_caching: ReadWrite
        managed_disk_type: Standard_LRS
        network_interface_names:
          - "{{ item.name }}-nic"
      loop:
        - { name: "VM-Front-End" }
        - { name: "VM-Back-End" }
        - { name: "VM-Stepping-Stone" }