---
- name: Azure Infrastructure Cleanup
  hosts: localhost
  connection: local
  vars:
    resource_group: KE02_groep02_RG
    location: West Europe
    virtual_network: TestVnet  # <<<----- ADD NAME OF VIRTUAL NETWORK TO DELETE

  tasks:
    # Delete Virtual Machines
    - name: Delete Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        state: absent
      loop:
        - { name: "VM-Front-End" }
        - { name: "VM-Back-End" }
        - { name: "VM-Stepping-Stone" }

        # Delete Network Interfaces
    - name: Delete Network Interfaces for Virtual Machine
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}-nic"
        state: absent
      loop:
        - { name: "VM-Front-End" }
        - { name: "VM-Back-End" }
        - { name: "VM-Stepping-Stone" }

        # Delete Network Security Groups (NSGs)
    - name: Delete Network Security Groups (NSGs)
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        state: absent
      loop:
        - { name: "NSG-Front-End" }
        - { name: "NSG-Back-End" }
        - { name: "NSG-Stepping-Stone" }

        # Delete subnets
    - name: Delete subnets
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network: "{{ virtual_network }}"
        name: "{{ item }}"
        state: absent
      loop:
        - "Front-End"
        - "Back-End"
        - "Stepping-Stone"

        # Delete Virtual Network
    - name: Delete Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        state: absent